### PR TITLE
feat: Redesign get_list_action with helper methods; pass tests 003/00…

### PR DESCRIPTION
**Pull request by oliverheisel**
…4/005

### CODE REVIEW

**Review by jaronimas-codes — CHANGES_REQUESTED** [review]
Test 001/002 does not pass, even last version it does. Check the merge conflict.

**Comment by undercover-hslu** [comment]
Merge conflicts checked and resolved. Tests 1,2,3,4,5,6 running positive

**Review by jaronimas-codes — APPROVED** [review]

**Comment by jaronimas-codes** [comment]
Hoi, testing this branch separately, tests are passed, but when I merge, only test 001 passes. Any ideas why?

**Comment by undercover-hslu** [comment]
Screenshot 2024-12-05 104614
Tests passed on my side

**Pull request merged**
